### ISSUE TITLE
Update via Octoprint fails

### ISSUE THREAD

**Issue by philverghese** [jukebox42/Octoprint-PrusaMMU#16]
I think there's an incorrect URL specified somewhere. Here's the error log I get when I try to update to 2022.8.22 via Octoprint.

The URL in the log below is https://github.com/jukebox42/Octoprint-PrusaMMU/releases/2022.8.22/download/Octoprint-PrusaMmu.zip which gives a 404 not found error. 

I think the correct URL is https://github.com/jukebox42/Octoprint-PrusaMMU/releases/download/2022.8.22/Octoprint-PrusaMmu.zip

```
Updating, please wait.
++++++++++++++++++++++++++++++++++
Now updating prusammu to 2022.8.22
++++++++++++++++++++++++++++++++++
/home/pi/oprint/bin/python3 -m pip --disable-pip-version-check install https://github.com/jukebox42/Octoprint-PrusaMMU/releases/2022.8.22/download/Octoprint-PrusaMmu.zip --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://github.com/jukebox42/Octoprint-PrusaMMU/releases/2022.8.22/download/Octoprint-PrusaMmu.zip
ERROR: HTTP error 404 while getting https://github.com/jukebox42/Octoprint-PrusaMMU/releases/2022.8.22/download/Octoprint-PrusaMmu.zip
ERROR: Could not install requirement https://github.com/jukebox42/Octoprint-PrusaMMU/releases/2022.8.22/download/Octoprint-PrusaMmu.zip because of HTTP error 404 Client Error: Not Found for url: https://github.com/jukebox42/Octoprint-PrusaMMU/releases/2022.8.22/download/Octoprint-PrusaMmu.zip for URL https://github.com/jukebox42/Octoprint-PrusaMMU/releases/2022.8.22/download/Octoprint-PrusaMmu.zip
The update did not finish successfully. Please consult <code>octoprint.log</code> and <code>plugin_softwareupdate_console.log</code> for details.
```

**Comment by jukebox42** [comment]
Ah, yep. I broke this in earlier version of the plugin. Fixed as of 2022.8.17. 

I unfortunately can't push a change to fix anyone who downloaded earlier versions. If you uninstall and reinstall it'll fix the issue moving forward.

thanks for the report tho! Let me know if you see this issue again after manually upgrading.
