### ISSUE TITLE
Future Considerations

### ISSUE THREAD

**Issue by jukebox42** [jukebox42/Octoprint-PrusaMMU#6]
New Features
- Handle print failures, these end up with the filament staying loaded so we should remember that and show it's still loaded.
- Give users a way in settings to clear out the mmu state
- Add color names so it's easier to select them.
- Add type to filament in settings (maybe?)
- Add gcode support

Plumbing
- Move filament sources out of settings
- Move gcode data out of settings (gcode not yet available but the base is there already)

Feel free to comment below with features you'd like to see. Or open a pull request.

**Comment by cvengels** [comment]
I'm always a fan of written names.
In this case, the color names.
Maybe in the future it's possible to merge these libraries into the project.
My own knowledge of JS is too bad atm :,)

https://github.com/meodai/color-names
https://github.com/dtao/nearest-color

**Comment by jukebox42** [comment]
@cvengels I didn't go full color names yet but have added a better color picker with reasonable default values to save time.
