### ISSUE TITLE
Spool Manager

### ISSUE THREAD

**Issue by naibaF5891** [jukebox42/Octoprint-PrusaMMU#7]
Hi 
I love the idea and I see this as improvement over the PlugIn  "MMU2 Select Filament", but an Integration with existing spool managers would be extremely helpful. I for example am already managing my filament with the "Spool Manager" PlugIn.
Thank you and cheers
Fabian

**Comment by jukebox42** [comment]
Good idea, let me add it to the list, if spool manager exposes a way to get that info I don't see why I couldn't add that integration.

**Comment by naibaF5891** [comment]
You could check the "MMU2 Select Filament" Plugin for some input, there this is handled like this.

**Comment by tonysurma** [comment]
+1 to above, I use the MMU2 Select Filament Plugin and it works with Filament Manager (what I use) as well for the filament names.

This plugin looks potentially more helpful than the select filament plugin so thanks in advance!

**Comment by jukebox42** [comment]
Just published a version that adds support for both of these. I did some testing myself but I don't use either of them day to day so I wouldn't mind feedback :)

I also think I broke the version check in the last version so you might have to force an update(or download the latest below)

https://github.com/jukebox42/Octoprint-PrusaMMU/releases/download/2022.8.14/Octoprint-PrusaMmu.zip

**Comment by schroding3r** [comment]
Seems like it's not quite working for me. When I begin a print, I get a popup asking if I'd like to use a given spool, but then it never seems to give that answer back to Octoprint. It waited for me to select a filament at the printer.

On a second test print, I set a default filament, and it waited for 30 seconds before selecting the default.
Please let me know if there are any other logs or anything I can provide you and thank you for a great plugin, it's so close to being _exactly_ what I needed.

**Comment by jukebox42** [comment]
@schroding3r can you tell me what version you are running and if you are using SpoolManager or filamentmanager as your source? Was the title of the dialog you got Prusa MMU(as in did it look like the screenshot on the readme)?

(Also thank you for trying it! I wanna get this integration right)

Update: I have a hunch the "Reminder for verifying the selected spool." setting in SpoolManager is suppressing the Prusa MMU selection dialog. Can you confirm if this setting is enabled/disabled for you as well? (if you are using SpoolManager)

**Comment by schroding3r** [comment]
Ah I was running 8.12 somehow, but updated to 8.14 and disabled that reminder and now it gave me the proper spool selection pop up. It didn't give me the spool names or colors, just "1 2 3 4 5".

Spoolmanager does it's index starting from 0, so a checkbox to toggle start at 0/1 would be great too (if it's not too much to ask)!

Again, thank you so much. I'll continue to report and be happy to test.

**Comment by jukebox42** [comment]
Interesting, So it should be displaying the names and colors from spoolmanager, if it's falling back to the numbers then it hit the failsafe(anything's better than nothing). Let me add a few more debug lines and share a version you can try. Appreciate the testing!

**Comment by jukebox42** [comment]
@schroding3r I've added an alpha version that exposes some debug features available at this link:

[PR Link #12](https://github.com/jukebox42/Octoprint-PrusaMMU/pull/12)

At the bottom of the Prusa MMU settings, you'll see a debug setting. Turning that on will cause Prusa MMU to write a bunch of debug information into the browser's console log. When you get a chance could you give the new version a try with debug on and send me a screenshot of the devtools console? It should look something like this:
![Screenshot 2022-08-17 190813](https://user-images.githubusercontent.com/654820/185259164-25682688-73ee-4d58-be7d-d4f3bff084be.png)

I tested it a few times with spoolmanager and was able to see my spools so I'm curious where it's failing. Could you also confirm the version of spoolmanager you are using is the most up to date?

**Comment by schroding3r** [comment]
Is this what you're looking for? 
![image](https://user-images.githubusercontent.com/427957/185261664-4213bd47-aa85-42a7-b464-8d1973923993.png)

Is it ok if I just give you the screenshot instead of submitting a new issue? ;)
Also yes, Spoolmanager 1.7.0
When I start a print that message appears a few more times, etc. I'm fairly confidant it's your devil.
Thank you again for your efforts!

**Comment by jukebox42** [comment]
@schroding3r perfect! Ok, new version available in the PR, please test when you get a sec :)

**Comment by schroding3r** [comment]
Just gave that one an install and kicked a print off, looked great. Colors and names pulled. Thanks so much!

**Comment by jukebox42** [comment]
thank you for the help! I'm going to resolve this issue now. I've released 2022.8.20 which includes the changes above. Don't forget to enable indexAtZero if you want your tools to report at 0-4 instead of 1-5(purely cosmetic) :)

https://github.com/jukebox42/Octoprint-PrusaMMU/releases/tag/2022.8.20
