### ISSUE TITLE
Filament information from G-Code

### ISSUE THREAD

**Issue by cvengels** [jukebox42/Octoprint-PrusaMMU#8]
Hi :)

When you export your print file you get lots of info about the used filament(s) in the comments at the end.
Maybe it would be possible to extract these and add them to the settings for each print (instead of manually setting the color and material)?

PrusaSlicer: 
![Screenshot 2022-08-03 031135](https://user-images.githubusercontent.com/6281096/182503627-b18fee38-673b-4c81-9f1a-7d215b474826.png)

First is the custom filament color you chose, second is the material color:
![Screenshot 2022-08-03 031516](https://user-images.githubusercontent.com/6281096/182503625-9c27bfa3-a864-47e6-9533-6e2f288928f4.png)

Basic material name:
![Screenshot 2022-08-03 031559](https://user-images.githubusercontent.com/6281096/182503620-2a9d18f3-1bb4-40c8-9e0c-d48b4a2b5191.png)

Product name:
![Screenshot 2022-08-03 031539](https://user-images.githubusercontent.com/6281096/182503624-6305f265-10fc-447f-a9e9-e3e6868b5470.png)

Thanks!

**Comment by peterjhl** [comment]
+1

**Comment by jukebox42** [comment]
Moving to under consideration. I like this idea but it's proven to be a bit too big for the last few releases.

**Comment by jukebox42** [comment]
Editing for clarity:
- single slice prints do have a color in the file, it's a single color that was used when slicing.
- you can manually update gcode files to change the filament colors, they're quite parsable.

Original message:
This feature is not currently planned so closing the open issue. Since the color data isnt available in single prints the user would still need to define it in the plugin, and changing the colors in an already sliced file isnt possible, so the data from the gcode would be fairly inaccurate the longer the file stayed on their octoprint.

**Comment by cvengels** [comment]
> Since the color data isnt available in single prints ...

It took me less than minute to find the filament color in the gcode file from a non MMU print.
Don't see any problem here why not to implement it.

![image](https://github.com/jukebox42/Octoprint-PrusaMMU/assets/6281096/ac3ae96c-b035-4689-bf29-8a90a799d128)

> changing the colors in an already sliced file isnt possible

Why not? Search with an regex filter for the colors, they are listed in order of the extruders. Find and change them, then you have a different color.

**Comment by jukebox42** [comment]
Sorry, you are right, in a single slice print a single color is there in the source. I noticed that too. But, it's only one color, sure it's there, but doesn't that defeat the purpose of having a modal to let you select what filament to use if it'll always assume it's that single color? Unless you plan to always print the same gcode with the exact same filament color, I don't think it'll be a very reliable feature.

As for changing the colors, yes, true you can edit the file. Gcode is easy to parse and read. But it's already been uploaded to octoprint. So each time you change your mmu colors, or want to print it in another color you could download the file, edit it, and reupload it. Or edit on the server through some plugin. But that's essentially what you can do today with the plugin without having to remember to update your files.

This feature could certainly be built. But I'm sorry, I don't see the value of trying to read the gcode data. It's more likely to be inaccurate the longer the gcode file exists in your octoprint unless you consistently keep the same colors in the same spots.

Did not mean to spread misinformation. I'll add an addendum to my previous comment.
